name: Build Android App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sparkfabrik/android-build-action@v1.3.4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        build-type: assemble
        gradle-task: assembleRelease
        increment-build-number: 1.0.0
        package-name: com.example.weatherapp
        project-path: app/src/main
        output-path: weather app.apk
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
